department/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import TableView, promotion_position

app_name = "departments"

urlpatterns = [
    path("table/", TableView.as_view(), name="table"),
    path("table/ws/<int:pk>/", promotion_position, name="promotion"),
]

quizes/urls.py
from django.urls import path
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view, HomePageView

app_name = "quizes"

urlpatterns = [
    path("", HomePageView.as_view(), name="main-view"),
    path("list/", QuizListView.as_view(), name="quiz-list"),
    path("list/<pk>/", quiz_view, name="quiz-view"),
    path("list/<pk>/save/", save_quiz_view, name="save-view"),
    path("list/<pk>/data/", quiz_data_view, name="quiz-data-view"),
]

recruitment_personnel/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "quizes/",
        include("quizes.urls"),
    ),
    path("profile/", include("profiles.urls")),
    path('department/', include('department.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

department/models.py
from django.db import models

# Create your models here.


class Departments(models.Model):
    department_name = models.CharField(max_length=80, default='department name')

    count_person = models.IntegerField(default=0)

    MAX_PERSON = models.IntegerField(default=0)
    MIN_PERSON = models.IntegerField(default=0)

    def __str__(self):
        return self.department_name

    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'


class Positions(models.Model):
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)

    position = models.CharField(max_length=30, default='position')

    count_person = models.IntegerField(default=0)

    MAX_PERSON = models.IntegerField(default=0)
    MIN_PERSON = models.IntegerField(default=0)

    def __str__(self):
        return self.position

    class Meta:
        verbose_name = 'Position'
        verbose_name_plural = 'Positions'

department/views.py
from django.shortcuts import render
from django.views.generic import ListView

# models
from .models import Positions

# scripts
from .scripts.filters import (
    get_profile_promotions,
    profile_promotions_list,
    promotion_list,
)

import itertools


class TableView(ListView):
    template_name = "departments/table.html"
    queryset = Positions.objects.filter(count_person__lt=12)
    context_object_name = "query_results"


def promotion_position(request, pk):
    position = Positions.objects.get(pk=pk)

    profiles = get_profile_promotions(position)
    profile_list = profile_promotions_list(profiles)

    to_promotion = promotion_list(
        position.MAX_PERSON, position.count_person, profile_list
    )

    for employee in to_promotion:
        previously_pos = Positions.objects.get(position=employee.position)
        previously_pos.count_person -= 1
        previously_pos.save()

        new_pos = position

        employee.position = new_pos
        employee.save()

        new_pos.count_person += 1
        new_pos.save()

    return render(
        request,
        "departments/table2.html",
        context={
            "choose": to_promotion,
            "new_pos": position.position,
        },
    )

templates/departments/table.html
{% extends "base.html" %}
{% block title %}
<title>Title</title>

{% endblock %}

{% block scripts %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block content %}
    <div class="panel-body table-responsive">
    <table class="table">
        <tr>
            <th>Отдел</th>
            <th>Должность</th>
            <th>Минимальное количество</th>
            <th>Текущее количество</th>
            <th>Максимальное количество</th>
            <th>Заявка</th>
        </tr>

        {% for item in query_results %}
            <tr>
                <td>{{ item.department.department_name }}</td>
                <td>{{ item.position }}</td>
                <td>{{ item.MIN_PERSON }}</td>
                <td>{{ item.count_person }}</td>
                <td>{{ item.MAX_PERSON }}</td>
                <td>
                    <ul class="action-list">
                        <li><a href="{% url 'departments:promotion' item.pk %}"><i class="fa fa-users"></i></a></li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

templates/departments/table2.html
{% extends "base.html" %}

{% block title %}
    <title>Таблица 2</title>
{% endblock %}

{% block scripts %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style type="text/css">
        table {
          border-collapse: collapse;
          border: 1px solid black;
        }

        th, td {
          padding: 8px;
        }
        .cell-highlight {
          background-color: gold;
          font-weight: bold;
        }
        html, body { margin: 0; padding: 0; }
        div { margin: 5px; text-align: center; }
        #box { position: absolute; width: 200px; }
        #left { position: absolute; }
        #right { position: relative; float: right; }
    </style>
{% endblock %}

{% block content %}
    <div class=".col-md-6">
        <div class="panel-body table-responsive">
            <table class="table">
                <tr>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Текущий Отдел</th>
                    <th> </th>
                </tr>
                    {% for item in choose %}
                        <tr class="table-active">
                            <td>{{ item.first_name }}</td>
                            <td>{{ item.last_name }}</td>
                            <td>{{ new_pos }}</td>
                            <td><i class="fa fa-check"></i></td>
                        </tr>
                    {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}