department/urls.py
from django.urls import path
from django.urls import reverse_lazy
from .views import TableView, promotion_position

app_name = "departments"

urlpatterns = [
    path("table/", TableView.as_view(), name="table"),
    path("table/ws/<int:pk>/", promotion_position, name="promotion"),
]

profiles/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from .views import login_view, ProfilesList, ProfileDetail

app_name = "profiles"

urlpatterns = [
    path(
        "login/",
        login_view,
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page=reverse_lazy("profiles:profiles_list")),
        name="logout",
    ),
    path("profiles/", ProfilesList.as_view(), name='profiles_list'),
    path('profile/<int:pk>/', ProfileDetail.as_view(), name='profile_detail')
]

quizes/urls.py
from django.urls import path
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view, HomePageView

app_name = "quizes"

urlpatterns = [
    path("", HomePageView.as_view(), name="main-view"),
    path("list/", QuizListView.as_view(), name="quiz-list"),
    path("list/<pk>/", quiz_view, name="quiz-view"),
    path("list/<pk>/save/", save_quiz_view, name="save-view"),
    path("list/<pk>/data/", quiz_data_view, name="quiz-data-view"),
]

recruitment_personnel/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "quizes/",
        include("quizes.urls"),
    ),
    path("profile/", include("profiles.urls")),
    path('department/', include('department.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

     {% block scripts %}
    {% endblock %}

    {% block title %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light fixed-top shadow">
        <div class="container navbar-container"><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse me-auto" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="#">Главная</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'profiles:login' %}">Логин</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'profiles:profiles_list'%}">Пользователи</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'departments:table' %}">Заявки</a></li>
                </ul>
            </div><a class="login-button" href="{% url 'profiles:login' %}"><button class="align-self-start btn btn-primary" type="submit">Войти</button></a>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>