profiles/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from .views import login_view, ProfilesList, ProfileDetail

app_name = "profiles"

urlpatterns = [
    path(
        "login/",
        login_view,
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page=reverse_lazy("profiles:profiles_list")),
        name="logout",
    ),
    path("profiles/", ProfilesList.as_view(), name='profiles_list'),
    path('profile/<int:pk>/', ProfileDetail.as_view(), name='profile_detail')
]

quizes/urls.py
from django.urls import path
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view, HomePageView

app_name = "quizes"

urlpatterns = [
    path("", HomePageView.as_view(), name="main-view"),
    path("list/", QuizListView.as_view(), name="quiz-list"),
    path("list/<pk>/", quiz_view, name="quiz-view"),
    path("list/<pk>/save/", save_quiz_view, name="save-view"),
    path("list/<pk>/data/", quiz_data_view, name="quiz-data-view"),
]

recruitment_personnel/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "quizes/",
        include("quizes.urls"),
    ),
    path("profile/", include("profiles.urls")),
    path('department/', include('department.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


from department.models import Departments, Positions
from phonenumber_field.modelfields import PhoneNumberField
from datetime import datetime

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    last_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=30)
    father_name = models.CharField(max_length=30)

    date_of_birth = models.DateField(default=datetime.now)
    years_old = models.IntegerField(default=0)

    phone = PhoneNumberField(default="Phone number")
    login = models.CharField(max_length=30, default="login")
    email = models.EmailField(default="Mail address")

    pasportNum = models.CharField(max_length=15, default="Pasport num")
    pasportCode = models.CharField(max_length=15, default="Pasport code")
    pasportOtd = models.CharField(max_length=50, default="Pasport otd")
    pasportDate = models.CharField(max_length=15, default="Pasport date")

    inn_fiz = models.CharField(max_length=15, default="inn")
    oms = models.CharField(max_length=16, default="oms")

    address = models.CharField(max_length=50, default="Address")
    country = models.CharField(max_length=50, default="Country")
    region = models.CharField(max_length=50, default="Region")
    city = models.CharField(max_length=50, default="City")

    photo = models.ImageField(upload_to="personnel_photos")

    department = models.ForeignKey(
        Departments, on_delete=models.CASCADE, null=True, blank=True
    )
    position = models.ForeignKey(
        Positions, on_delete=models.CASCADE, null=True, blank=True
    )

    seniority = models.IntegerField(default=0)
    company_seniority = models.IntegerField(default=0)
    specialized_education = models.BooleanField(default=False)
    additional_courses = models.IntegerField(
        help_text="Часы прохождения дополнительных курсов", default=0
    )
    reprimands = models.IntegerField(default=0)

    if_dismissed = models.BooleanField(default=False)

    def __str__(self):
        return f"Profile of the {self.user.username}"

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Username"}
        ),
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        ),
    )

    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Repeat Password"}
        ),
        help_text="Enter the same password as above, for verification.",
    )

    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "email"}
        ),
    )

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(
            attrs={"class": "form-control login-form", "placeholder": "Логин", 'type': 'login'}
        ),
    )

    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control pswd-form", "placeholder": "Пароль", 'type': 'password'}
        ),
    )

    class Meta:
        model = User
        fields = ("username", "password")

profiles/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.utils.safestring import mark_safe
from django.contrib import messages
from django.views.generic import ListView, DetailView

from .forms import RegistrationForm, LoginForm
from .models import Profile


'''def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)

        check = request.POST.get("check-reg", None)

        if form.is_valid() and (check == "true"):
            form.save()
            login(
                request,
                user=authenticate(
                    username=form.cleaned_data["username"],
                    password=form.cleaned_data["password1"],
                ),
            )
            return redirect("quizes:main-view")
        else:
            error_text = "<ul>"

            for msg_list in form.errors.values():
                for msg in msg_list:
                    error_text += f"<li>{msg}</li>"
            if check != "true":
                error_text += "<li>Вы не подтвердили согласие на регистрацию</li>"
            error_text += "</ul>"

            messages.error(request, mark_safe(error_text))

    else:
        form = RegistrationForm()

    context = {"form": form}
    return render(request, "users/register.html", context)'''


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd["username"], password=cd["password"]
            )
            if user is not None:
                if user.is_active:
                    login(request, user=user)
                    return redirect(reverse_lazy("profiles:profiles_list"))
            else:
                error_text = "<label class='form-label error-form'>Неправильный логин или пароль</label>"
                messages.error(request, mark_safe(error_text))
    else:
        form = LoginForm()

    context = {"form": form}
    return render(request, "profiles/login.html", context)


class ProfilesList(ListView):
    model = Profile
    template_name = "profiles/accounts.html"
    context_object_name = "profile_list"
    paginate_by = 10


class ProfileDetail(DetailView):
    model = Profile
    template_name = 'profiles/single-account.html'
    context_object_name = 'profile'

templates/profiles/accounts.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Аккаунты</title>
{% endblock %}

{% block content %}
    <h3 class="text-center mt-5 border-bottom pt-5 pb-4 shadow-sm">Пользователи</h3>

    {% if profile_list %}
    <div class="container item-block my-2 p-4 col-11 col-sm-8 border rounded-3">
        {% for profile in profile_list %}
        <a class="account-card" href={% url 'profiles:profile_detail' profile.pk %}>
            <div class="card m-2">
                <img class="card-img-top" src="{{ profile.photo.url }}" />
                <div class="card-body">
                    <div class="h5 card-title">{{ profile.last_name }} {{ profile.first_name }} {{ profile.father_name }}</div>
                    <p class="card-text">Бухгалтер</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    {% endif %}

    {% if is_paginated %}
    <div class="container mb-5 col-12 col-sm-8">
        <ul class="pagination flex-wrap justify-content-center pb-5">

            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="/profile/profiles?page={{ page_obj.previous_page_number }}">Назад</a></li>
            {% endif %}

            {% for page in paginator.page_range %}
                {% if page_obj.number == page %}
                    <li class="page-item active"><a class="page-link" href="/profile/profiles?page={{ page }}" disabled>{{ page }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="/profile/profiles?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="/profile/profiles?page={{ page_obj.next_page_number }}">Вперёд</a></li>
            {% endif %}

        </ul>
    </div>
    {% endif %}

    <div>
    </div>
{% endblock %}

templates/profiles/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Логин</title>{% endblock %}

{% block content %}
<div class="py-5"></div>
    <div class="container form-container col-lg-3 col-md-5 col-sm-6 col-6 p-4 border shadow rounded-3">
        <form method="post">

            {% csrf_token %}

            <h3>Вход</h3>
            <div class="my-3">{{ form.username }}</div>
            <div class="my-3">{{ form.password }}</div>

            {% if messages %}
                <div id="my-3 text-center">
                    {% for message in messages %}
                            {{ message|safe }}
                    {% endfor %}
                </div>
            {% else %}
                <div id="my-3 text-center"></div>
            {% endif %}

            <div class="my-3"><button class="btn btn-primary mx-auto d-block" type="submit">Войти</button></div>
        </form>
        </div>
    <div>
</div>
{% endblock %}

templates/profiles/single-account.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Просмотр Аккаунта</title>
{% endblock %}

{% block content %}
    <div class="p-3"></div>
    <div class="container border my-5 col-sm-12 col-md-10 col-lg-9 col-xl-8 col-xxl-7">
        <div class="row">
            <div class="col-md-5 border-end p-lg-5 card-left-side">
                <div class="image my-2"><img class="w-100" src="{{ profile.photo.url }}"></div>
                <div class="px-2 p-lg-0">
                    <div class="display-6 country">{{ profile.country }}</div>
                    <p class="region">{{ profile.region }}</p>
                    <p class="lead city">{{ profile.city }}</p>
                    <p class="phone">{{ profile.phone }}</p>
                </div>
            </div>
            <div class="col-md-7 p-5">
                <div class="h2 full-name">{{ profile.last_name }} {{ profile.first_name }} {{ profile.father_name }}</div>
                <div class="text-end">
                    <div class="col-8 border-bottom ms-auto my-3"></div>
                    <div class="h4 age">Возраст: {{ profile.years_old }}</div>
                    <div class="h5 login">Логин: {{ profile.login }}</div>
                    <div class="h5 email">Email: {{ profile.email }}</div>
                    <div class="col-8 border-bottom ms-auto my-3"></div>
                </div>
                <p class="inn">ИНН: {{ profile.inn_fiz }}</p>
                <p class="oms">ОМС: {{ profile.oms }}</p>
                <div class="col-11 col-md-12 col-lg-11 col-xl-10 border rounded-1 p-3 passport-card">
                    <p class="passport float-end mt-2">{{ profile.pasportNum}} {{ profile.pasportCode }}</p>
                    <p class="h4">Паспорт</p><label class="form-label">Паспорт выдан: </label><textarea class="form-control passport-otdel text-uppercase" type="passport-otdel" rows="6">{{ profile.pasportOtd}}</textarea>
                    <p class="passport-date">Дата выдачи: {{ profile.pasportDate }}</p>
                    <p class="birthday">Дата рождения: {{ profile.date_of_birth }}</p>
                </div>
            </div>
        </div>
    </div>
    <div></div>
{% endblock %}